Repository cvpaperchallenge/Ascender, pull requests merged in 2022-08, with the labels that each got.

#51 docs: add questions to FAQ
  README.md
  environments/Dockerfile
  poetry.toml
Labels: documentation

#54 feat: use poetry 1.2 beta
  README.md
  environments/Dockerfile
  environments/cpu/docker-compose.yaml
  environments/gpu/docker-compose.yaml
Labels: enhancement

#55 feat: merge develop branch into master
  README.md
  environments/Dockerfile
  environments/cpu/docker-compose.yaml
  environments/gpu/docker-compose.yaml
  poetry.toml
Labels: enhancement

#57 docs: Update README.md
  README.md
Labels: documentation, chore

#59 chore: Add data directory
  data/README.md
Labels: chore
