Repository cvpaperchallenge/Ascender, pull requests merged in 2022-10, with the labels that each got.

#70 fix typo
  README.md
Labels: documentation

#72 67/fix/add condition to target markdown files
  Makefile
Labels: bug

#69 67/enh/introduce markdown formatter
  .github/ISSUE_TEMPLATE/development.md
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  README.md
  data/README.md
  models/README.md
  notebooks/README.md
  outputs/README.md
  poetry.lock
  pyproject.toml
Labels: enhancement

#75 74/chore/fix typo in a html file
  build/index.html
Labels: chore

#80 77/docs/update readme
  README.md
Labels: documentation

#79 78/chore/use tool.poetry.group.dev.dependencies
  poetry.lock
  pyproject.toml
Labels: chore
