Repository cvpaperchallenge/Ascender, pull requests merged in 2022-07, with the labels that each got.

#29 #14/docs: move docs resource to britannica
  README.md
  slidev/.gitignore
  slidev/.npmrc
  slidev/README.md
  slidev/components/Counter.vue
  slidev/netlify.toml
  slidev/package-lock.json
  slidev/package.json
  slidev/public/ascender-github-create-from-template.png
  slidev/public/ascender-github-root-use-this-template.png
  slidev/public/ascender-github-root.png
  slidev/public/poetry-hp.png
  slidev/slides.md
  slidev/vercel.json
Labels: documentation

#28 Add watch to Makefile for using --watch option of node-sass
  Makefile
Labels: enhancement

#27 Create Citation section
  build/index.html
  src/sass/main.scss
Labels: enhancement

#31 Migrate to use package.json and npm script
  .gitignore
  Dockerfile
  Makefile
  README
  package-lock.json
  package.json
Labels: enhancement

#34 feat: add author component.
  build/index.html
  src/sass/main.scss
Labels: enhancement

#36 Implement Carousel Slider Component
  .editorconfig
  build/ascender.js
  build/index.html
  package.json
  src/sass/main.scss
Labels: enhancement

#37 feat: add button feature
  build/index.html
  src/sass/main.scss
Labels: enhancement

#39 fix: add UID and GID to build arg.
  README.md
  environments/Dockerfile
  environments/cpu/docker-compose.yaml
  environments/gpu/docker-compose.yaml
Labels: bug

#40 Set default text color
  src/sass/main.scss
Labels: enhancement

#42 feat: replace placeholder by actual value
  build/index.html
  src/sass/main.scss
Labels: enhancement

#44 feat: add draft contents
  build/ascender.js
  build/index.html
  src/sass/main.scss
Labels: enhancement

#45 Add meta tags for og and twitter card and favicon
  build/index.html
  build/manifest.json
Labels: enhancement

#47 Implement CSS class to align item top as option of side-by-side class.
  build/index.html
  src/sass/main.scss
Labels: enhancement

#46 chore: add meta data
  build/index.html
Labels: enhancement

#48 Show brand logo
  build/index.html
  src/sass/main.scss
Labels: enhancement

#50 Fix Carousel slider; show dots
  build/ascender.js
  build/index.html
Labels: bug
